version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tournament
      POSTGRES_USER: tournament
      POSTGRES_PASSWORD: tournament
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tournament_user -d tournament_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: postgresql://tournament:tournament@postgres:5432/tournament_db
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   restart: unless-stopped

volumes:
  postgres_data: